name: 'Move Jira issue when PR closed'

description: 'This action change status of jira issue when PR closed and adding comment with build number'

inputs:
  jira-action:
    description: 'Action to do'
    required: true

runs:
  using: 'node12'
  main: 'index.js'